### ISSUE TITLE
Can't log in?

### ISSUE THREAD

**Issue by dbrewood** [barnstee/UA-CloudCommander#11]
Hi guys I'm a new user to Cloud Commander. It's installed on my Synology NAS and seemed to be working well.
It was installed into Portainer using this guide: https://mariushosting.com/how-to-install-cloud-commander-on-your-synology-nas/

I wanted to edit the \etc\hosts file and I had thought I'd done it correctly. However on a reboot the changes I'd made were overwritten. I posted the problem on the Synology forum and they advised that I needed to be logged in as the root user to get the changes to stick.
I went into the settings and clicked on authentication. I now get prompted for a user and a password. The issue is any accounts I try to log in with fail. I've tried:

- 'root' using the 'Admin' account password. 
- 'admin' using the 'Admin' account password. 
- my 'usual admin account

And none of them work. Each time I try and access Cloud Commander I hit the log in prompts so I'm somewhat stuck.

Any assistance would be greatly appreciated.

**Comment by barnstee** [comment]
Wrong Cloud Commander. You want to log your issue here: https://github.com/coderaiser/cloudcmd/issues
