### ISSUE TITLE
How to publish the configured topic to the commander?

### ISSUE THREAD

**Issue by liwuyang-pxc** [barnstee/UA-CloudCommander#6]
I have already configure the command topic and response topic via `MQTT_TOPIC` and `MQTT_RESPONSE_TOPIC` and the commander also running as the log print "UA Cloud Commander is running".
But the commander can't subscribe to the configured topic to receive commands.
Publish the topic(`MQTT_TOPIC=UaCloudCommander`) from the MQTT client like this :
`mosquitto_pub --cafile /var/snap/mosquitto/common/my-ca.crt --tls-version tlsv1.1 -h 127.0.0.1 -p 8883 -t 'UaCloudCommander/Read/?$rid=123' -m '{"Endpoint": "opc.tcp://192.168.2.10","NodeId": "nsu=http://phoenixcontact.com/OpcUA/PLCnext/Devices/;s=ThisDevice.Manufacturer"}'`
I can subscribe to this topic from another client:
`mosquitto_sub --cafile /var/snap/mosquitto/common/my-ca.crt --tls-version tlsv1.1 -h 127.0.0.1 -p 8883 -t 'UaCloudCommander/Read/?$rid=123' -v `
The above works and already confirmed.
But when subscribe the response topic(`MQTT_RESPONSE_TOPIC=UaCloudCommanderRes`) from another MQTT client like this:
`mosquitto_sub --cafile /var/snap/mosquitto/common/my-ca.crt --tls-version tlsv1.1 -h 127.0.0.1 -p 8883 -t 'UaCloudCommanderRes/200/?$rid=123' -v`
Nothing printed both from the commander log file  and the `mosquitto_sub` terminal.

Could you please help me to check if there is something wrong or missing? :)

**Comment by barnstee** [comment]
I assume you also see the line "Connected to MQTT broker." in the log, otherwise, your broker connection did not work. Regarding the topic, can you try the topic name "UaCloudCommander/#"? Also, you should see "Unknown command received:" in the log, if the topic name didn't work.

**Comment by liwuyang-pxc** [comment]
Hello, barnstee, Thanks for your reply :). Yes, I can see the "Connected to MQTT broker.". Sorry for my stupid question, should I publish the topic like this: mosquitto_pub -t 'UaCloudCommander/#'? Since I tried to publish the topic "UaCloudCommander/#" 
but "#" is a wildcard character and how  should I do?

**Comment by barnstee** [comment]
No, you should configure Ua Cloud Commander with the topic MQTT_TOPIC=UaCloudCommander/#

**Comment by barnstee** [comment]
then publish to that topic from an MQTT client like so:
mosquitto_pub --cafile /var/snap/mosquitto/common/my-ca.crt --tls-version tlsv1.1 -h 127.0.0.1 -p 8883 -t 'UaCloudCommander/Read/?$rid=123' -m '{"Endpoint": "opc.tcp://192.168.2.10","NodeId": "nsu=http://phoenixcontact.com/OpcUA/PLCnext/Devices/;s=ThisDevice.Manufacturer"}'

**Comment by liwuyang-pxc** [comment]
Oh, I see, Now it worked! Thank you very much! I can successfully read data from the OPC-UA server via the response topic after I modify the "MQTT_TOPIC" as "MQTT_TOPIC=UaCloudCommander/#".
