### ISSUE TITLE
Connection timed out over8883

### ISSUE THREAD

**Issue by srjhunjhunwalacorp** [barnstee/UA-CloudCommander#7]
Hello Team,

Is there an option to configure this over web socket instead of 8883 as it is blocked in most of the corporate firewalls?  Just curious to know if I am missing something on environment variables? I tried setting UseTLS to TRUE.
Also, from IoT hub do I need to direct method on the device to pass the parameters?

Rgds
SId

**Comment by barnstee** [comment]
I've added WebSocket support to UA Cloud Publisher that shares the same MQTT client code, so this needs to be ported over to UA Cloud Commander. Give me a day or two...

**Comment by barnstee** [comment]
This is fixed with https://github.com/OPCFoundation/UA-CloudCommander/commit/9092035d354618521cdcf261b931a75632f35cad. Yes, use direct methods. I'm still checking with IoT Hub team if WebSockets are supported with plain MQTT.

**Comment by srjhunjhunwalacorp** [comment]
Thanks a lot it works perfectly, In the documentation under usage container image needs a correction.

barnstee to opcfoundation

**Comment by barnstee** [comment]
Path to container image is now fixed. Thanks!
